---
title: ""

header-includes:
   - \usepackage{caption}
   - \usepackage{fullminipage}
   - \usepackage{graphicx}
   - \usepackage{wrapfig}
   - \usepackage{booktabs}
   - \usepackage{array}
   - \usepackage{placeins}
   - \usepackage{xcolor}
   - \usepackage{etoolbox}
   - \usepackage{float}
   - \usepackage{threeparttable}
   
output: 
 word_document:
    reference_docx: www/Landscape.docx
fontsize: 11
documentclass: article

params:
  outChk:  outChk
  olistID: olistID
  olevel:  olevel
  oObj: oObj
---

```{r setup,results="asis",include = FALSE} 
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results='asis',
                      fig.width=7,
                      fig.height=3) 

library(tidyverse, quietly=TRUE)
library(scales, quietly=TRUE)
library(officer, quietly=TRUE)
library(flextable, quietly=TRUE)

muffleError <- function(x,options) {}
knit_hooks$set(error=muffleError)

 outChk <- params$outChk  # List of topical areas
 olistID <- params$olistID # Place List
 olevel <- params$olevel # Output Level
 oObj <- params$oObj # List of Output objects

 # Setting up
ctyfips <- as.character(as.numeric(substr(olistID$list1,3,5)))
# Adding entry for multi county agency
if(length(ctyfips) > 1) {
 ctyfips <- c("0",ctyfips)
}

base <- 10 
```

# Community Services Block Grant Dashboard Report
### Print Date: `r format(Sys.Date(),"%m/%d/%Y")`



## Summary Report for `r olevel`


```{r age1, results="asis",  echo = FALSE}
if("age" %in% unlist(outChk)) {
    age_list <- oObj[[1,1]]
    age_data <- age_list[[1]]$data
    age_table <- age_list[[1]]$FlexTable
    age_caption <- age_list[[1]]$caption
    age_title <- unlist(oObj[[1,2]])
 
    age_title <- paste0(age_title,",\n",olistID$plName1)
    cat ("### Population by Age\n")
}
```



```{r age2, results="asis", echo = FALSE}

if("age" %in% unlist(outChk)) {
for(i in 1:length(ctyfips)) {
    age_data2 <- age_data[which(age_data$county == ctyfips[i]),]
 
    age_data2$age_cat <- factor(age_data2$age_cat, levels=c("00 to 04", "05 to 17", "18 to 64", "65+"))
    age_data2$age_pct <- age_data2$age_pct * 100
    maxLim <- max(age_data2$age_pct) + 20
    
    LocName <- unique(age_data2$geoname)
    ggimg1 <- age_data2 %>% ggplot(aes(x=age_cat, y=age_pct)) +
    geom_bar(stat="identity", position="dodge", color="black", fill="blue")+
          scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
           theme_codemog(base_size=base) +
           labs(title = age_title,
                subtitle = LocName,
                caption = age_caption,
                x = "Age Category",
                y= "Percentage") +
           theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                 panel.background = element_rect(fill = "white", colour = "gray50"),
                 panel.grid.major = element_line(colour = "gray80"),
                 axis.text.x = element_text(size=10),
                 axis.text.y=element_text(size=12))
    print(ggimg1)
    
}

}

```

##### PAGE BREAK

```{r age3, results="asis", echo = FALSE}
if("age" %in% unlist(outChk)) {
  cat(knit_print(age_table))
}

```

##### PAGE BREAK

```{r ageemp1, results="asis",  echo = FALSE}
if("ageemp" %in% unlist(outChk)) {
    ageemp_list <- oObj[[2,1]]
    ageemp_data <- ageemp_list[[1]]$data
    ageemp_table <- ageemp_list[[1]]$FlexTable
    ageemp_caption <- ageemp_list[[1]]$caption
    ageemp_title <- unlist(oObj[[2,2]])
 
    ageemp_title <- paste0(ageemp_title,",\n",olistID$plName1)
    ageemp_title2 <- paste0("Age Distribution by Percentage\nin Civilian Labor Force,\n",olistID$plName1)
    ageemp_title3 <- paste0("Age Distribution by Percentage Unemployed,\n",olistID$plName1)
    
cat("### Age by Employment Status\n")
}
```

```{r ageemp2, results="asis", echo = FALSE}

if("ageemp" %in% unlist(outChk)) {
   for(i in 1:length(ctyfips)) {
       ageemp_data2 <- ageemp_data[which(ageemp_data$county == ctyfips[i] & ageemp_data$type == "In Civilian Labor Force"),]
       ageemp_data3 <- ageemp_data[which(ageemp_data$county == ctyfips[i] & ageemp_data$type == "Unemployed"),]
       
       ageemp_data2$type <- factor(ageemp_data2$type, levels=c("16 to 19", "20 to 64", "65+"))
       ageemp_data3$type <- factor(ageemp_data3$type, levels=c("16 to 19", "20 to 64", "65+"))
       
       ageemp_data2$pct <- ageemp_data2$pct * 100
       ageemp_data3$pct <- ageemp_data3$pct * 100
       
       maxLim2 <- max(ageemp_data2$pct) + 20
       maxLim3 <- max(ageemp_data3$pct) + 20
       
       LocName <- unique(ageemp_data2$geoname)
       ggimg2a <-ggplot(ageemp_data2, aes(x=age_cat, y=pct)) +
       geom_bar(stat="identity", position="dodge", color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim2), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = ageemp_title2,
                   subtitle = LocName,
                   caption = ageemp_caption,
                   x = "Age Category",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12),
                    legend.position= "none")
       print(ggimg2a)
       
       ggimg2b <-ggplot(ageemp_data3, aes(x=age_cat, y=pct)) +
       geom_bar(stat="identity", position="dodge", color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim3), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = ageemp_title3,
                   subtitle = LocName,
                   caption = ageemp_caption,
                   x = "Age Category",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12),
                    legend.position= "none")
       print(ggimg2b)
    
}

}

```

##### PAGE BREAK

```{r ageemp3, results="asis", echo = FALSE}
if("ageemp" %in% unlist(outChk)) {
  cat(knit_print(ageemp_table))
}

```

##### PAGE BREAK

```{r pov1, results="asis",  echo = FALSE}
if("pov" %in% unlist(outChk)) {
    pov_list <- oObj[[3,1]]
    pov_data <- pov_list[[1]]$data
    pov_table <- pov_list[[1]]$FlexTable
    pov_caption <- pov_list[[1]]$caption
    pov_title <- unlist(oObj[[3,2]])
 
    pov_title <- paste0(pov_title,",\n",olistID$plName1)
    
cat("### Population by Federal Poverty Level\n")
}
```

```{r pov2, results="asis", echo = FALSE}

if("pov" %in% unlist(outChk)) {
   for(i in 1:length(ctyfips)) {
       pov_data2 <- pov_data[which(pov_data$county == ctyfips[i]),]
       
       pov_data2$pct <- pov_data2$value * 100
       maxLim <- max(pov_data2$pct) + 20
       
       LocName <- unique(pov_data2$geoname)
       ggimg3 <-ggplot(pov_data2, aes(x=POV.LEVEL, y=pct)) +
       geom_bar(stat="identity", position="dodge", color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = pov_title,
                   subtitle = LocName,
                   caption = pov_caption,
                   x = "Percentage of Federal Poverty Level",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12),
                    legend.position= "none")
    print(ggimg3)
}

}

```

##### PAGE BREAK

```{r pov3, results="asis", echo = FALSE}
if("pov" %in% unlist(outChk)) {
  cat(knit_print(pov_table))
}

```

##### PAGE BREAK

```{r educatt1, results="asis",  echo = FALSE}
if("educatt" %in% unlist(outChk)) {
    educatt_list <- oObj[[4,1]]
    educatt_data <- educatt_list[[1]]$data
    educatt_table <- educatt_list[[1]]$FlexTable
    educatt_caption <- educatt_list[[1]]$caption
    educatt_title <- unlist(oObj[[4,2]])
 
    educatt_title <- paste0(educatt_title,",\n",olistID$plName1)
    
cat("### Educational Attainment by Federal Poverty Level\n")
}
```

```{r educatt2, results="asis", echo = FALSE}

if("educatt" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
       educatt_data2 <- educatt_data[which(educatt_data$county == ctyfips[i]),]
        educatt_data2$educatt <- plyr::revalue(educatt_data2$educatt,  
                                               c("Less Than High School"="Less Than\nHigh School",
                         "High School Graduate" = "High School\nGraduate",
                         "Some College, Associates Degree" = "Some College,\nAssociates Degree",
                         "Bachelor's Degree or Higher" = "Bachelor's Degree\nor Higher"))
       educatt_data2$educatt <-  factor(educatt_data2$educatt, levels=c("Less Than\nHigh School",
                 "High School\nGraduate",
                  "Some College,\nAssociates Degree",
                    "Bachelor's Degree\nor Higher")) 
       
       educatt_data2$value <- educatt_data2$value * 100
       maxLim <- max(educatt_data2$value) + 20
       
       LocName <- unique(educatt_data2$geoname)
       ggimg4 <-ggplot(educatt_data2, aes(x=educatt, y=value, fill=lvl)) +
       geom_bar(stat="identity", position="dodge")+
             scale_fill_manual(values=c("#00953A","#6EC4E8"),
                      name="Poverty Level") +
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = educatt_title,
                   subtitle = LocName,
                   caption = educatt_caption,
                   x = "Educational Attainment",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
     print(ggimg4)
    }
}

```

##### PAGE BREAK

```{r educatt3, results="asis", echo = FALSE}
if("educatt" %in% unlist(outChk)) {
  cat(knit_print(educatt_table))
}

```

##### PAGE BREAK

```{r povage1, results="asis",  echo = FALSE}
if("povage" %in% unlist(outChk)) {
    povage_list <- oObj[[5,1]]
    povage_data <- povage_list[[1]]$data
    povage_table <- povage_list[[1]]$FlexTable
    povage_caption <- povage_list[[1]]$caption
    povage_title <- unlist(oObj[[5,2]])
 
    povage_title <- paste0(povage_title,",\n",olistID$plName1)
    
cat("### Age by Federal Poverty Level\n")
}
```

```{r povage2, results="asis", echo = FALSE}
if("povage" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
       povage_data2 <- povage_data[which(povage_data$fips == ctyfips[i]),]
       povage_data2$age_cat <- factor(povage_data2$age_cat , levels= c("5 to 17", "18 and Older", "Total"))
      
       povage_data2$value <- povage_data2$value * 100
       maxLim <- max(povage_data2$value) + 20
       
       LocName <- unique(povage_data2$geoname)
       ggimg5 <-ggplot(povage_data2, aes(x=age_cat, y=value)) +
       geom_bar(stat="identity", position="dodge",  color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = povage_title,
                   subtitle = LocName,
                   caption = povage_caption,
                   x = "Age Category",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                    plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
       print(ggimg5)
    }
}

```

##### PAGE BREAK

```{r povage3, results="asis", echo = FALSE}
if("povage" %in% unlist(outChk)) {
  cat(knit_print(povage_table))
}

```

##### PAGE BREAK

```{r povagetr1, results="asis",  echo = FALSE}
if("povagetr" %in% unlist(outChk)) {
    povagetr_list <- oObj[[6,1]]
    povagetr_data <- povagetr_list[[1]]$data
    povagetr_table <- povagetr_list[[1]]$FlexTable
    povagetr_caption <- povagetr_list[[1]]$caption
    povagetr_title <- unlist(oObj[[6,2]])
 
    povagetr_title <- paste0(povagetr_title,",\n",olistID$plName1)
    
cat("### Age by Federal Poverty Level Trend\n")
}
```

```{r povagetr2, results="asis", echo = FALSE}
if("povagetr" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
       povagetr_data2 <- povagetr_data[which(povagetr_data$fips == ctyfips[i]),]
       povagetr_data2$age_cat <- factor(povagetr_data2$age_cat , levels= c("5 to 17", "18 and Older", "All Persons"))
      
       povagetr_data2$value <- povagetr_data2$value * 100
       maxLim <- max(povagetr_data2$value) + 10
       
       LocName <- unique(povagetr_data2$geoname)
       ggimg6 <-ggplot(povagetr_data2, aes(x=year, y=value, color=age_cat)) +
       geom_line(size=1.2) +
             scale_color_manual(values=c("blue","orange","green"), name="Age Category") +
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = povagetr_title,
                   subtitle = LocName,
                   caption = povagetr_caption,
                   x = "Year",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                    plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
       print(ggimg6)
    }
}

```

##### PAGE BREAK

```{r povagetr3, results="asis", echo = FALSE}
if("povagetr" %in% unlist(outChk)) {
  cat(knit_print(povagetr_table))
}

```

##### PAGE BREAK

```{r povagedis1, results="asis",  echo = FALSE}
if("povagedis" %in% unlist(outChk)) {
    povagedis_list <- oObj[[7,1]]
    povagedis_data <- povagedis_list[[1]]$data
    povagedis_table <- povagedis_list[[1]]$FlexTable
    povagedis_caption <- povagedis_list[[1]]$caption
    povagedis_title <- unlist(oObj[[7,2]])
 
    povagedis_title <- paste0(povagedis_title,",\n",olistID$plName1)
    
cat("### Age by Federal Poverty Level for Persons with Disabilities\n")
}
```

```{r povagedis2, results="asis", echo = FALSE}
if("povagedis" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
       povagedis_data2 <- povagedis_data[which(povagedis_data$county == ctyfips[i] & povagedis_data$meas == "Below Poverty Level" ),]
       povagedis_data2$age_cat <- factor(povagedis_data2$age_cat , levels= c("Under 18", "18 to 64", "65+", "Total"))
      
       povagedis_data2$pct <- as.numeric(sub("%","",povagedis_data2$pct))
       
       maxLim <- max(povagedis_data2$pct) + 20
       
       LocName <- unique(povagedis_data2$geoname)
       ggimg7 <-ggplot(povagedis_data2, aes(x=age_cat, y=pct)) +
       geom_bar(stat="identity", position="dodge",  color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = povagedis_title,
                   subtitle = LocName,
                   caption = povagedis_caption,
                   x = "Age Category",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
       print(ggimg7)
    }
}

```

##### PAGE BREAK

```{r povagedis3, results="asis", echo = FALSE}
if("povagedis" %in% unlist(outChk)) {
  cat(knit_print(povagedis_table))
}

```

##### PAGE BREAK

```{r hhpov1, results="asis",  echo = FALSE}
if("hhpov" %in% unlist(outChk)) {
    hhpov_list <- oObj[[8,1]]
    hhpov_data <- hhpov_list[[1]]$data
    hhpov_table <- hhpov_list[[1]]$FlexTable
    hhpov_caption <- hhpov_list[[1]]$caption
    hhpov_title <- unlist(oObj[[8,2]])
 
    hhpov_title <- paste0(hhpov_title,",\n",olistID$plName1)
    
cat("### Families by Type and Poverty Status\n")
}
```

```{r hhpov2, results="asis", echo = FALSE}
if("hhpov" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
      hhpov_data2 <- hhpov_data[which(hhpov_data$county == ctyfips[i]),]
       
       hhpov_data2$pct <- hhpov_data2$pct * 100
       
       maxLim <- max(hhpov_data2$pct) + 20
       
       LocName <- unique(hhpov_data2$geoname)
      ggimg8 <-ggplot(hhpov_data2, aes(x=famtype, y=pct, fill=kids)) +
       geom_bar(stat="identity", position="dodge")+
             scale_fill_manual(values=c("#00953A","#6EC4E8"),
                      name="Presence of Children") +
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = hhpov_title,
                   subtitle = LocName,
                   caption = hhpov_caption,
                   x = "Family Type",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
       print(ggimg8)
    }
}

```

##### PAGE BREAK

```{r hhpov3, results="asis", echo = FALSE}
if("hhpov" %in% unlist(outChk)) {
  cat(knit_print(hhpov_table))
}

```

##### PAGE BREAK

```{r tenure1, results="asis",  echo = FALSE}
if("tenure" %in% unlist(outChk)) {
    tenure_list <- oObj[[9,1]]
    tenure_data <- tenure_list[[1]]$data
    tenure_table <- tenure_list[[1]]$FlexTable
    tenure_caption <- tenure_list[[1]]$caption
    tenure_title <- unlist(oObj[[9,2]])
 
    tenure_title <- paste0(tenure_title,",\n",olistID$plName1)
    
cat("### Housing Tenure by Poverty Status\n")
}
```

```{r tenure2, results="asis", echo = FALSE}
if("tenure" %in% unlist(outChk)) {
    for(i in 1:length(ctyfips)) {
    tenure_data2 <- tenure_data[which(tenure_data$county == ctyfips[i] ),]
       
       tenure_data2$pct <- tenure_data2$pct * 100
       
       maxLim <- max(tenure_data2$pct) + 20
       
       LocName <- unique(tenure_data2$geoname)
      ggimg9 <-ggplot(tenure_data2, aes(x=famtype, y=pct, fill=tenure)) +
       geom_bar(stat="identity", position="dodge")+
             scale_fill_manual(values=c("#00953A","#6EC4E8"),
                      name="Housing Tenure") +
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = tenure_title,
                   subtitle = LocName,
                   caption = tenure_caption,
                   x = "Family Type",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
      print(ggimg9)
    }
}

```

##### PAGE BREAK

```{r tenure3, results="asis", echo = FALSE}
if("tenure" %in% unlist(outChk)) {
  cat(knit_print(tenure_table))
}

```

##### PAGE BREAK

```{r snap1, results="asis",  echo = FALSE}
if("snap" %in% unlist(outChk)) {
    snap_list <- oObj[[10,1]]
    snap_data <- snap_list[[1]]$data
    snap_table <- snap_list[[1]]$FlexTable
    snap_caption <- snap_list[[1]]$caption
    snap_title <- unlist(oObj[[10,2]])
 
    snap_title <- paste0(snap_title,",\n",olistID$plName1)
    
cat("### Supplemental Nutrition Assistance Program (SNAP)\n")
}
```

```{r snap2, results="asis", echo = FALSE}
if("snap" %in% unlist(outChk)) {
   for(i in 1:length(ctyfips)) {
      snap_data2 <- snap_data[which(snap_data$fips == ctyfips[i] ),]
       
       snap_data2$pct <- snap_data2$pct * 100
       
       maxLim <- max(snap_data2$pct) + 20
     
       
       LocName <- unique(snap_data2$county)
     ggimg10 <-ggplot(snap_data2, aes(x=SNAP, y=pct)) +
       geom_bar(stat="identity", position="dodge",  color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = snap_title,
                   subtitle = LocName,
                   caption = snap_caption,
                   x = "Program Participation",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
      print(ggimg10)
    }
}

```

##### PAGE BREAK

```{r snap3, results="asis", echo = FALSE}
if("snap" %in% unlist(outChk)) {
  cat(knit_print(snap_table))
}

```

##### PAGE BREAK

```{r wic1, results="asis",  echo = FALSE}
if("wic" %in% unlist(outChk)) {
    wic_list <- oObj[[11,1]]
    wic_data <- wic_list[[1]]$data
    wic_table <- wic_list[[1]]$FlexTable
    wic_caption <- wic_list[[1]]$caption
    wic_title <- unlist(oObj[[11,2]])
 
    wic_title <- paste0(wic_title,",\n",olistID$plName1)
    
cat("### Women, Infants and Children (WIC)\n")
}
```

```{r wic2, results="asis", echo = FALSE}
if("wic" %in% unlist(outChk)) {
   for(i in 1:length(ctyfips)) {
       wic_data2 <- wic_data[which(wic_data$fips == ctyfips[i] ),]
       
       wic_data2$pct <- wic_data2$pct * 100
       
       maxLim <- max(wic_data2$pct) + 20
       
       LocName <- unique(wic_data2$county)
     ggimg11 <-ggplot(wic_data2, aes(x=WIC, y=pct)) +
       geom_bar(stat="identity", position="dodge",  color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = wic_title,
                   subtitle = LocName,
                   caption = wic_caption,
                   x = "Program Participation",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
      print(ggimg11)
    }
}

```

##### PAGE BREAK

```{r wic3, results="asis", echo = FALSE}
if("wic" %in% unlist(outChk)) {
  cat(knit_print(wic_table))
}

```

##### PAGE BREAK

```{r insurance1, results="asis",  echo = FALSE}
if("insurance" %in% unlist(outChk)) {
    insurance_list <- oObj[[12,1]]
    insurance_data <- insurance_list[[1]]$data
    insurance_table <- insurance_list[[1]]$FlexTable
    insurance_caption <- insurance_list[[1]]$caption
    insurance_title <- unlist(oObj[[12,2]])
 
    insurance_title <- paste0(insurance_title,",\n",olistID$plName1)
    
cat("### Health Insurance by Source\n")
}
```

```{r insurance2, results="asis", echo = FALSE}
if("insurance" %in% unlist(outChk)) {
   for(i in 1:length(ctyfips)) {
       insurance_data2 <- insurance_data[which(insurance_data$fips == ctyfips[i] ),]
       
       insurance_data2$ins <- plyr::revalue(insurance_data2$ins, c( "Uninsured" = "Uninsured",
                                                       "Employer Sponsored" = "Employer\nSponsored",
                                                        "Medicaid" = "Medicaid",
                                                        "Individually Purchased" = "Individually\nPurchased" ,
                                                         "Child Health Plan Plus" = "Child Health\nPlan Plus"))
      insurance_data2$ins <- factor(insurance_data2$ins, levels = c( "Individually\nPurchased",
                                                           "Employer\nSponsored", 
                                                           "Medicaid",
                                                          "Uninsured",
                                                          "Child Health\nPlan Plus"))

       
       insurance_data2$pct <- insurance_data2$pct * 100
       
       maxLim <- max(insurance_data2$pct) + 20

       LocName <- unique(insurance_data2$county)
     ggimg12 <-ggplot(insurance_data2, aes(x=ins, y=pct)) +
       geom_bar(stat="identity", position="dodge",  color="black", fill="blue")+
             scale_y_continuous(limits = c(0, maxLim), label=percent, expand = c(0, 0)) +
              theme_codemog(base_size=base) +
              labs(title = insurance_title,
                   subtitle = LocName,
                   caption = insurance_caption,
                   x = "Type of Insurance",
                   y= "Percentage") +
              theme(plot.title = element_text(hjust = 0.5, size=12),
                 plot.caption = element_text(hjust = 0, size=9),
                    panel.background = element_rect(fill = "white", colour = "gray50"),
                    panel.grid.major = element_line(colour = "gray80"),
                    axis.text.x = element_text(size=10),
                    axis.text.y=element_text(size=12))
      print(ggimg12)
    }
}

```

##### PAGE BREAK

```{r insurance3, results="asis", echo = FALSE}
if("insurance" %in% unlist(outChk)) {
  cat(knit_print(insurance_table))
}

```